language: java
notifications:
  email:
    if: type = cron OR branch = master
    recipients:
      - windup-eng@redhat.com
    on_success: change
    on_failure: always
jdk:
  - openjdk8

env:
  - TEST_SUITE=units
  - TEST_SUITE=integration

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test -P $TEST_SUITE
  - echo $TEST_SUITE

#jobs:
#  include:
#    - stage: Test
#      script:
#        - mvn test
