language: java
notifications:
  email:
    if: type = cron OR branch = master
    recipients:
      - windup-eng@redhat.com
    on_success: change
    on_failure: always
jdk:
  - openjdk8

env:
  global:
    - CAMEL_SPRINGBOOT_TRACING=false
    - LOGGING_LEVEL_ROOT=info
    - ANALYSIS_DATAINTEGRITY_LOG=false
  jobs:
    - TEST_SUITE=units
    - TEST_SUITE=native

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test
  - echo $TEST_SUITE


